all:
  hosts:
    k8s_test_master:
      ansible_host: 172.16.0.17
      ip: 172.16.0.17
      access_ip: 172.16.0.17
    k8s_test_worker:
      ansible_host: 172.16.0.18
      ip: 172.16.0.18
      access_ip: 172.16.0.18
  children:
    kube_control_plane:
      hosts:
        k8s_test_master:
    kube_node:
      hosts:
        k8s_test_worker:
    etcd:
      hosts:
        k8s_test_master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
