all:
  hosts:
    k8s_test_master:
      ansible_host: 10.98.10.11
      ip: 10.98.10.11
      access_ip: 10.98.10.11
    k8s_test_worker:
      ansible_host: 10.98.10.21
      ip: 10.98.10.21
      access_ip: 10.98.10.21
  children:
    kube_control_plane:
      hosts:
        k8s_test_master:
    kube_node:
      hosts:
        k8s_test_worker:
    etcd:
      hosts:
        k8s_test_master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
